---
title: "DATA_613_Shiny_App_Project"
author: "Sunday Okechukwu"
date: "2023-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(shiny)
library(ggthemes)
library(lubridate)
```

```{r}
hr <- read_csv("HRDataset_v14.csv")
hr
```
```{r}
hr %>% 
  mutate(DateofHiretrans = year(mdy(DateofHire))) -> hr
```

```{r}
hr %>% 
  ggplot(aes(x = Sex, y = Salary, fill=Sex)) %>% +
  geom_boxplot()+
  stat_summary(fun = mean, geom = "point", shape = 20, size = 3, color = "red", fill = "red")+
scale_fill_colorblind()+
  theme_bw() +
  facet_wrap(~Department)
```

```{r}
library(ggplot2)

hr %>% 
  ggplot(aes(x = EmpSatisfaction)) +
  geom_bar() +
  stat_count(aes(label = after_stat(count)), geom = "text", vjust = -1) +
  scale_fill_colorblind() +
  theme_bw() + 
  coord_flip()

```


```{r}
ui <- fluidPage(
  titlePanel("Putting things together"),
  selectInput("vars", "HR Variables", choices = names(hr)),
  
  selectInput("var", "HR Variables", choices = unique(x)),
  plotOutput("plot"),
)

server <- function(input, output) {
  output$plot <- renderPlot({
    ggplot(hr, aes(x = .data[[input$vars]])) +
      geom_bar(color = "blue") +
        stat_count(aes(label = after_stat(count)), geom = "text", vjust = -1) +
  scale_fill_colorblind() +
  theme_bw() + 
  coord_flip() +
      ggtitle("Human Resources Plot") 
  })
}

shinyApp(ui = ui, server = server)
```

```{r}
library(ggplot2)

ggplot(hr, aes(x = Sex, y = Salary, color = )) +
  geom_point() +
  labs(x = "Years Since Graduation", y = "Salary", color = "Position") +
  theme_bw()

```

